{ pkgs ? import <nixpkgs> {} }:

let
  wasi = pkgs.pkgsCross.wasi32;
in
pkgs.mkShell {
  packages = with pkgs; [
    arduino-cli
    platformio
    python3
    git
    jq
    curl
    wasm-tools
  ] ++ [
    wasi.stdenv.cc
  ];

  shellHook = ''
    export ARDUINO_DATA_DIR="$PWD/.arduino15"
    export ARDUINO_DIRECTORIES_DATA="$ARDUINO_DATA_DIR"
    export WASI_SDK_PATH="${wasi.stdenv.cc}"
    export CC="${wasi.stdenv.cc}/bin/${wasi.stdenv.cc.targetPrefix}clang"
    export CXX="${wasi.stdenv.cc}/bin/${wasi.stdenv.cc.targetPrefix}clang++"
    export PATH="$WASI_SDK_PATH/bin:$PWD/.local/bin:$PATH"

    mkdir -p "$ARDUINO_DATA_DIR" "$PWD/.local/bin" "$PWD/wokwi" "$PWD/chips"

    cat > "$PWD/chips/wokwi-api.h" <<'EOF'
// Generated by shell.nix. Minimal local Wokwi API declarations.
#ifndef WOKWI_API_H
#define WOKWI_API_H

#include <stdbool.h>
#include <stdint.h>

typedef uint32_t pin_t;
typedef uint32_t uart_dev_t;
typedef uint32_t timer_t;

typedef enum {
  INPUT,
  INPUT_PULLUP,
  OUTPUT,
} pin_mode_t;

typedef enum {
  LOW = 0,
  HIGH = 1,
} pin_value_t;

typedef enum {
  RISING,
  FALLING,
  BOTH,
} pin_edge_t;

typedef struct {
  pin_edge_t edge;
  void (*pin_change)(void *user_data, pin_t pin, uint32_t value);
  void *user_data;
} pin_watch_config_t;

typedef struct {
  pin_t tx;
  pin_t rx;
  uint32_t baud_rate;
  void *user_data;
} uart_config_t;

typedef struct {
  void (*callback)(void *user_data);
  void *user_data;
} timer_config_t;

typedef struct {
  uint32_t address;
  pin_t sda;
  pin_t scl;
  bool (*connect)(void *user_data, uint32_t address, bool read);
  uint8_t (*read)(void *user_data);
  bool (*write)(void *user_data, uint8_t data);
  void (*disconnect)(void *user_data);
  void *user_data;
} i2c_config_t;

pin_t pin_init(const char *name, pin_mode_t mode);
bool pin_read(pin_t pin);
void pin_watch(pin_t pin, const pin_watch_config_t *config);

uart_dev_t uart_init(const uart_config_t *config);
void uart_write(uart_dev_t uart, const uint8_t *buffer, uint32_t size);

timer_t timer_init(const timer_config_t *config);
void timer_start(timer_t timer, uint64_t duration_us, bool periodic);
void timer_stop(timer_t timer);

void i2c_init(const i2c_config_t *config);

#endif
EOF

    cat <<'EOF'
Entorno listo.

Compilar firmware para Wokwi:
  pio run

El binario debe quedar en:
  .pio/build/esp32doit-devkit-v1/firmware.bin

Luego abre el proyecto con la extensión de Wokwi en VS Code.
EOF
  '';
}
